import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import WrapReactQuary from "@/components/common/WrapReactQuary";
import CustomProvider from "@/redux/provider";
import {ThemeProvider} from "@/hooks/ThemeProvider";

export const revalidate = 3000;

export const metadata: Metadata = {
  title: "Nimeshregmi",
  description: "Generated by Nimeshregmi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{ maxWidth: "1700px" }}
        className={`$ {inter.className}   bg-[#F3F4F6] dark:bg-[#020D1A] text-black dark:text-white overflow-x-hidden w-screen`}
      >
        <CustomProvider>
          <WrapReactQuary>
            <ToastContainer theme="dark" autoClose={2000} closeOnClick />
            <>
              <main className="text-black  dark:text-white">
                <ThemeProvider>{children}</ThemeProvider>
              </main>
            </>
          </WrapReactQuary>
        </CustomProvider>
      </body>
    </html>
  );
}
